# Generated by Django 4.0.5 on 2022-06-28 19:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_start_time_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='repeat',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('week_days', (('SA', 'saturday'), ('MO', 'monday'), ('TU', 'tuesday'), ('WE', 'wednesday'), ('TH', 'thursday'), ('FR', 'friday'), ('SU', 'sunday'))), ('x_day_week', (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'))), ('x_day_month', (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')))], max_length=32),
        ),
    ]
