# Generated by Django 4.0.5 on 2022-06-30 11:01

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_habit_finished_alter_habit_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='repeat',
        ),
        migrations.AddField(
            model_name='habit',
            name='repeat_day',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SA', 'saturday'), ('MO', 'monday'), ('TU', 'tuesday'), ('WE', 'wednesday'), ('TH', 'thursday'), ('FR', 'friday'), ('SU', 'sunday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='repeat_month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='habit',
            name='repeat_week',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True),
        ),
    ]
